# Config for Dependabot updates. See Documentation here:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  # We need to specify each Dockerfile in a separate entry because Dependabot doesn't
  # support wildcards or recursively checking subdirectories. Check this issue for updates:
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `docker/local/django` directory
    directory: "docker/local/django/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `docker/local/docs` directory
    directory: "docker/local/docs/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `docker/local/node` directory
    directory: "docker/local/node/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `docker/production/aws` directory
    directory: "docker/production/aws/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `docker/production/django` directory
    directory: "docker/production/django/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `docker/production/postgres` directory
    directory: "docker/production/postgres/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `docker/production/traefik` directory
    directory: "docker/production/traefik/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"
