version: '3'
services:
    app:
        image: powermeter
        build:
            dockerfile: docker/Dockerfile
            context: .
            args:
                SYNC_ARGS: "--dev"
        env_file:
            -   ./docker/envs/.django
        environment:
            - DB_HOST=db
        ports:
            - "8000:8000"
